spring:
  datasource:
    url: jdbc:mysql://mysql:3306/edgepulse?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: edgepulse
    password: edgepulse
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379

edgepulse:
  mqtt:
    broker-url: tcp://mqtt:1883
